### ISSUE TITLE
GIF resolution

### ISSUE THREAD

**Issue by rcwachter** [shuuryou/kanji2gif#1]
Is there a way to change the resolution or are they all stuck at 109x109?

**Comment by shuuryou** [comment]
In Program.cs there are two constants on line 22;

```cs
private const int WIDTH = 109, HEIGHT = 109;
```

If you recompile the code you can choose any resolution you want. KanjiVG data is all vector-based so the GIF files should look crisp at any resolution.

**Comment by rcwachter** [comment]
> In Program.cs there are two constants on line 22;
> 
> ```cs
> private const int WIDTH = 109, HEIGHT = 109;
> ```
> 
> If you recompile the code you can choose any resolution you want. KanjiVG data is all vector-based so the GIF files should look crisp at any resolution.

I did see that, but I'm not able to compile the code, I tried downgrading Visual Studio and installing DotNet 4.0, but none of it worked. If you know how to help with that, please let me know, it would be greatly appreciated. Thanks.

**Comment by shuuryou** [comment]
_sigh_

It turns out that when I first wrote this, I hardcoded 109px in various places. The width and height constants are cute but weren't used everywhere. Please don't ask me why. If you changed them without changing the other places, the output looks totally weird.

Anyway, I've pushed a new build v1.1.0.1 that contains `/imgw:x` and `/imgh:x` command line arguments.

VS2022 won't build this without going from .NET 4.0 o .NET 4.8, but VS2019 was happy building it as-is with .NET 4.0.

Touching this code was downright embarrassing. Building SVG animations using strings... times sure were simpler back then. I wish I had the time and energy to give Kanji2GIF the overhaul it deserves, especially since newer versions of .NET allow cross-platform builds, but work and family are taking up 99% of my spare time atm. Sorry. 

I didn't have time to update the GUI, but you can call the EXE from the command prompt, e.g. like so:

`Kanji2GIF.exe yourwordlist.txt outputdir /c /imgw:500 /imgh:500`

Then you get:
![過労](https://github.com/shuuryou/kanji2gif/assets/36278767/226593b1-50ae-456f-b077-95c0ef220e75)

Be prepared to wait. Larger images take decidedly longer to generate. Luckily the file sizes don't grow out of control. The above GIF is under 30KB. Getting them stay small is why you need to wait so long.

Use `.` as the output directory if you want the GIF files in the same folder that the EXE lives in.

Don't use weird widths and heights that aren't square (width should equal height) or I don't know what will happen. Kanji2GIF will let you, but the output will probably be scaled incorrectly.

Hope this helps for your use case. Please test and let me know if it works.

**Comment by rcwachter** [comment]
Thanks for taking time to update this, everything works, but the GIF still stays small, but the canvas is bigger like this:
![奈](https://github.com/shuuryou/kanji2gif/assets/97169604/4267458b-65e0-4f5f-94cb-ff7554a96808)

Not sure why this happens but let me know if I did it wrong.

Here was my input:
Kanji2GIF.exe wordlist.txt /. /imgw:300 /imgh:300

**Comment by shuuryou** [comment]
Please try the build 1.1.0.2 attached below:
[Release_1102.zip](https://github.com/shuuryou/kanji2gif/files/14773882/Release_1102.zip)

* It treats the scaling factor as a decimal number rather than an integer. Scaling by 2.752293577981651 will yield a different result than scaling by 2.
* It also fixes the stroke guides to work with scaling. They now appear again.
* It adds a GUI setting to set the image size

With this build I was able to make animations for 奈 in any size and they look OK to me.

![sm奈](https://github.com/shuuryou/kanji2gif/assets/36278767/d7972dc3-cac0-4fa3-a7aa-4c5a925852fb)
![奈](https://github.com/shuuryou/kanji2gif/assets/36278767/8c40337a-f9db-4f21-bd6d-67424ada5c9f)
![hg奈](https://github.com/shuuryou/kanji2gif/assets/36278767/5ee289db-6c23-4d95-a125-54fb4090bc0a)

**Comment by rcwachter** [comment]
This is working perfectly now. I really appreciate you taking the time to fix this. Thank you so much!
